theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1: 'bold,italic,underline, strikethrough,|,forecolorpicker, numlist, bullist, indent, outdent, link, blockquote, emotions'
plugins: 
  - emotions